### ISSUE TITLE
Can we use this?

### ISSUE THREAD

**Issue by SKSaki** [noel-friedrich/terminal#15]
Is there any way i could get this and make modifications to it so i can remove the logo and just let it be a simple terminal?

**Comment by noel-friedrich** [comment]
Yes! The terminal contains a list of startup-commands (stored in the TerminalData object at terminal.data.startupCommands) that will each get executed each time the terminal starts (the default being `["turtlo --silent", "helloworld"]`). To remove the logo, simply replace the default to an empty list. The defaults are defined in the [filesystem.js](https://github.com/noel-friedrich/terminal/blob/main/js/filesystem.js) file, inside the TerminalData class under `defaultValues = ...`.

Btw, you can also modify the startupCommands while using the terminal using the `sc remove <command>` command. Run the following two commands to remove turtlo and the logo on your terminal:
```
sc remove "turtlo --silent"
sc remove helloworld
``` 
If you're searching for a simple terminal, this isn't the right project for you. This is my terminal website, a fun place with loads of features a simple terminal probably shouldn't have (easter-eggs, loads of games and personal projects). Also note that the default filesystem and loading screen (which also contains my logo!) is hardcoded aswell. The logic behind this terminal isn't that complicated: making your own from scratch is probably easier than modifying this one enough to be 'simple', since it contains a whole lot of code that isn't exactly necessary but rather just loads of fun :)
  
hope I could help!

**Comment by SKSaki** [comment]
Hey, 
Thanks for the kind response. I looked far and wide for this kind of terminal that has .js commands and basically all commads are programmable, opposite to terminals that have a file. 
I will actually use this more as a base for a future project.

**Comment by SKSaki** [comment]
Also i am a newb, so i still look around to understand the logic :))
